// Asset and Identity contracts — blueveil.contracts.v1.
// References between contracts use plain string IDs (asset_id, identity_id),
// not nested messages, so each entity can evolve without cascading changes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/asset.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED    AssetType = 0
	AssetType_ASSET_TYPE_HOST           AssetType = 1
	AssetType_ASSET_TYPE_CONTAINER      AssetType = 2
	AssetType_ASSET_TYPE_SERVICE        AssetType = 3
	AssetType_ASSET_TYPE_NETWORK        AssetType = 4
	AssetType_ASSET_TYPE_CLOUD_RESOURCE AssetType = 5
	AssetType_ASSET_TYPE_USER_DEVICE    AssetType = 6
	AssetType_ASSET_TYPE_OTHER          AssetType = 7
	// Step 13A additions (appended values only; existing numbers untouched).
	AssetType_ASSET_TYPE_DOMAIN      AssetType = 8
	AssetType_ASSET_TYPE_IP_ADDRESS  AssetType = 9
	AssetType_ASSET_TYPE_URL         AssetType = 10
	AssetType_ASSET_TYPE_APPLICATION AssetType = 11
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0:  "ASSET_TYPE_UNSPECIFIED",
		1:  "ASSET_TYPE_HOST",
		2:  "ASSET_TYPE_CONTAINER",
		3:  "ASSET_TYPE_SERVICE",
		4:  "ASSET_TYPE_NETWORK",
		5:  "ASSET_TYPE_CLOUD_RESOURCE",
		6:  "ASSET_TYPE_USER_DEVICE",
		7:  "ASSET_TYPE_OTHER",
		8:  "ASSET_TYPE_DOMAIN",
		9:  "ASSET_TYPE_IP_ADDRESS",
		10: "ASSET_TYPE_URL",
		11: "ASSET_TYPE_APPLICATION",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED":    0,
		"ASSET_TYPE_HOST":           1,
		"ASSET_TYPE_CONTAINER":      2,
		"ASSET_TYPE_SERVICE":        3,
		"ASSET_TYPE_NETWORK":        4,
		"ASSET_TYPE_CLOUD_RESOURCE": 5,
		"ASSET_TYPE_USER_DEVICE":    6,
		"ASSET_TYPE_OTHER":          7,
		"ASSET_TYPE_DOMAIN":         8,
		"ASSET_TYPE_IP_ADDRESS":     9,
		"ASSET_TYPE_URL":            10,
		"ASSET_TYPE_APPLICATION":    11,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_asset_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_asset_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_asset_proto_rawDescGZIP(), []int{0}
}

// Lifecycle status (Step 13A). Linear flow with documented revival:
// DISCOVERED → ACTIVE → STALE → RETIRED, plus STALE → ACTIVE on
// re-observation and ACTIVE → RETIRED for direct dismissal. RETIRED is
// terminal. STALE means "unobserved lately", never "dead".
type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_DISCOVERED  AssetStatus = 1
	AssetStatus_ASSET_STATUS_ACTIVE      AssetStatus = 2
	AssetStatus_ASSET_STATUS_STALE       AssetStatus = 3
	AssetStatus_ASSET_STATUS_RETIRED     AssetStatus = 4
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_UNSPECIFIED",
		1: "ASSET_STATUS_DISCOVERED",
		2: "ASSET_STATUS_ACTIVE",
		3: "ASSET_STATUS_STALE",
		4: "ASSET_STATUS_RETIRED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_UNSPECIFIED": 0,
		"ASSET_STATUS_DISCOVERED":  1,
		"ASSET_STATUS_ACTIVE":      2,
		"ASSET_STATUS_STALE":       3,
		"ASSET_STATUS_RETIRED":     4,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_asset_proto_enumTypes[1].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_asset_proto_enumTypes[1]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_asset_proto_rawDescGZIP(), []int{1}
}

// One verifiable identifier for an asset, e.g. {type: "ipv4", value: "127.0.0.1"}.
type AssetIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetIdentifier) Reset() {
	*x = AssetIdentifier{}
	mi := &file_blueveil_contracts_v1_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetIdentifier) ProtoMessage() {}

func (x *AssetIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetIdentifier.ProtoReflect.Descriptor instead.
func (*AssetIdentifier) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_asset_proto_rawDescGZIP(), []int{0}
}

func (x *AssetIdentifier) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AssetIdentifier) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable Blueveil-side identifier, e.g. "asset-waf-sim-01".
	Id          string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        AssetType          `protobuf:"varint,2,opt,name=type,proto3,enum=blueveil.contracts.v1.AssetType" json:"type,omitempty"`
	Name        string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Identifiers []*AssetIdentifier `protobuf:"bytes,4,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	// Business criticality of the asset (reuses the Severity scale).
	// Optional: unknown criticality is expressed by omitting the field,
	// never by sending SEVERITY_UNSPECIFIED.
	Criticality Severity `protobuf:"varint,5,opt,name=criticality,proto3,enum=blueveil.contracts.v1.Severity" json:"criticality,omitempty"`
	// Step 13A additions (all optional: pre-13A payloads stay valid).
	// Deployment context, e.g. "lab", "staging", "prod". Empty = unknown.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// Lifecycle status. Absent = unknown (legacy records); never UNSPECIFIED
	// when present.
	Status AssetStatus `protobuf:"varint,7,opt,name=status,proto3,enum=blueveil.contracts.v1.AssetStatus" json:"status,omitempty"`
	// First observation; set at creation, never mutated afterwards.
	FirstSeen *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=first_seen,proto3" json:"first_seen,omitempty"`
	// Most recent observation; bumped on every re-observation.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,proto3" json:"last_seen,omitempty"`
	// Source-supplied facts (never inferred scores or verdicts).
	Attributes    map[string]string `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_blueveil_contracts_v1_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_asset_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetIdentifiers() []*AssetIdentifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *Asset) GetCriticality() Severity {
	if x != nil {
		return x.Criticality
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Asset) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *Asset) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Asset) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Asset) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_blueveil_contracts_v1_asset_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_asset_proto_rawDesc = "" +
	"\n" +
	"!blueveil/contracts/v1/asset.proto\x12\x15blueveil.contracts.v1\x1a\"blueveil/contracts/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x0fAssetIdentifier\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xcf\x04\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .blueveil.contracts.v1.AssetTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12H\n" +
	"\videntifiers\x18\x04 \x03(\v2&.blueveil.contracts.v1.AssetIdentifierR\videntifiers\x12A\n" +
	"\vcriticality\x18\x05 \x01(\x0e2\x1f.blueveil.contracts.v1.SeverityR\vcriticality\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12:\n" +
	"\x06status\x18\a \x01(\x0e2\".blueveil.contracts.v1.AssetStatusR\x06status\x12:\n" +
	"\n" +
	"first_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"first_seen\x128\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tlast_seen\x12L\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2,.blueveil.contracts.v1.Asset.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb9\x02\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fASSET_TYPE_HOST\x10\x01\x12\x18\n" +
	"\x14ASSET_TYPE_CONTAINER\x10\x02\x12\x16\n" +
	"\x12ASSET_TYPE_SERVICE\x10\x03\x12\x16\n" +
	"\x12ASSET_TYPE_NETWORK\x10\x04\x12\x1d\n" +
	"\x19ASSET_TYPE_CLOUD_RESOURCE\x10\x05\x12\x1a\n" +
	"\x16ASSET_TYPE_USER_DEVICE\x10\x06\x12\x14\n" +
	"\x10ASSET_TYPE_OTHER\x10\a\x12\x15\n" +
	"\x11ASSET_TYPE_DOMAIN\x10\b\x12\x19\n" +
	"\x15ASSET_TYPE_IP_ADDRESS\x10\t\x12\x12\n" +
	"\x0eASSET_TYPE_URL\x10\n" +
	"\x12\x1a\n" +
	"\x16ASSET_TYPE_APPLICATION\x10\v*\x93\x01\n" +
	"\vAssetStatus\x12\x1c\n" +
	"\x18ASSET_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ASSET_STATUS_DISCOVERED\x10\x01\x12\x17\n" +
	"\x13ASSET_STATUS_ACTIVE\x10\x02\x12\x16\n" +
	"\x12ASSET_STATUS_STALE\x10\x03\x12\x18\n" +
	"\x14ASSET_STATUS_RETIRED\x10\x04b\x06proto3"

var (
	file_blueveil_contracts_v1_asset_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_asset_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_asset_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_asset_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_asset_proto_rawDesc), len(file_blueveil_contracts_v1_asset_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_asset_proto_rawDescData
}

var file_blueveil_contracts_v1_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blueveil_contracts_v1_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blueveil_contracts_v1_asset_proto_goTypes = []any{
	(AssetType)(0),                // 0: blueveil.contracts.v1.AssetType
	(AssetStatus)(0),              // 1: blueveil.contracts.v1.AssetStatus
	(*AssetIdentifier)(nil),       // 2: blueveil.contracts.v1.AssetIdentifier
	(*Asset)(nil),                 // 3: blueveil.contracts.v1.Asset
	nil,                           // 4: blueveil.contracts.v1.Asset.AttributesEntry
	(Severity)(0),                 // 5: blueveil.contracts.v1.Severity
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_blueveil_contracts_v1_asset_proto_depIdxs = []int32{
	0, // 0: blueveil.contracts.v1.Asset.type:type_name -> blueveil.contracts.v1.AssetType
	2, // 1: blueveil.contracts.v1.Asset.identifiers:type_name -> blueveil.contracts.v1.AssetIdentifier
	5, // 2: blueveil.contracts.v1.Asset.criticality:type_name -> blueveil.contracts.v1.Severity
	1, // 3: blueveil.contracts.v1.Asset.status:type_name -> blueveil.contracts.v1.AssetStatus
	6, // 4: blueveil.contracts.v1.Asset.first_seen:type_name -> google.protobuf.Timestamp
	6, // 5: blueveil.contracts.v1.Asset.last_seen:type_name -> google.protobuf.Timestamp
	4, // 6: blueveil.contracts.v1.Asset.attributes:type_name -> blueveil.contracts.v1.Asset.AttributesEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_asset_proto_init() }
func file_blueveil_contracts_v1_asset_proto_init() {
	if File_blueveil_contracts_v1_asset_proto != nil {
		return
	}
	file_blueveil_contracts_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_asset_proto_rawDesc), len(file_blueveil_contracts_v1_asset_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_asset_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_asset_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_asset_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_asset_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_asset_proto = out.File
	file_blueveil_contracts_v1_asset_proto_goTypes = nil
	file_blueveil_contracts_v1_asset_proto_depIdxs = nil
}
