// Blueveil contract layer — canonical definitions.
// Package: blueveil.contracts.v1
// See contracts/README.md for versioning, JSON mapping and design decisions.
// These contracts are owned by Blueveil. No Redveil model, schema or
// implementation detail is imported, copied or referenced here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity scale shared by telemetry, detections, alerts and incidents.
// The zero value is intentionally invalid: producers must set an explicit
// severity. JSON Schemas exclude SEVERITY_UNSPECIFIED from their enums,
// so a missing or defaulted severity fails runtime validation.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_common_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_common_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_blueveil_contracts_v1_common_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_common_proto_rawDesc = "" +
	"\n" +
	"\"blueveil/contracts/v1/common.proto\x12\x15blueveil.contracts.v1*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05b\x06proto3"

var (
	file_blueveil_contracts_v1_common_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_common_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_common_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_common_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_common_proto_rawDesc), len(file_blueveil_contracts_v1_common_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_common_proto_rawDescData
}

var file_blueveil_contracts_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blueveil_contracts_v1_common_proto_goTypes = []any{
	(Severity)(0), // 0: blueveil.contracts.v1.Severity
}
var file_blueveil_contracts_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_common_proto_init() }
func file_blueveil_contracts_v1_common_proto_init() {
	if File_blueveil_contracts_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_common_proto_rawDesc), len(file_blueveil_contracts_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_common_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_common_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_common_proto_enumTypes,
	}.Build()
	File_blueveil_contracts_v1_common_proto = out.File
	file_blueveil_contracts_v1_common_proto_goTypes = nil
	file_blueveil_contracts_v1_common_proto_depIdxs = nil
}
