// Detection → Alert → Incident contracts — blueveil.contracts.v1.
// Detection is the output of one rule over telemetry. Alert is a triage
// object over detections. Incident groups alerts for investigation.
// Response/Remediation lifecycle is intentionally NOT modelled here:
// it arrives as its own contract when the response engine is designed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/detection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_UNSPECIFIED  AlertStatus = 0
	AlertStatus_ALERT_STATUS_OPEN         AlertStatus = 1
	AlertStatus_ALERT_STATUS_ACKNOWLEDGED AlertStatus = 2
	AlertStatus_ALERT_STATUS_CLOSED       AlertStatus = 3
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_OPEN",
		2: "ALERT_STATUS_ACKNOWLEDGED",
		3: "ALERT_STATUS_CLOSED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED":  0,
		"ALERT_STATUS_OPEN":         1,
		"ALERT_STATUS_ACKNOWLEDGED": 2,
		"ALERT_STATUS_CLOSED":       3,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_detection_proto_enumTypes[0].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_detection_proto_enumTypes[0]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_detection_proto_rawDescGZIP(), []int{0}
}

type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_STATUS_UNSPECIFIED   IncidentStatus = 0
	IncidentStatus_INCIDENT_STATUS_OPEN          IncidentStatus = 1
	IncidentStatus_INCIDENT_STATUS_INVESTIGATING IncidentStatus = 2
	IncidentStatus_INCIDENT_STATUS_CONTAINED     IncidentStatus = 3
	IncidentStatus_INCIDENT_STATUS_RESOLVED      IncidentStatus = 4
	IncidentStatus_INCIDENT_STATUS_CLOSED        IncidentStatus = 5
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_STATUS_UNSPECIFIED",
		1: "INCIDENT_STATUS_OPEN",
		2: "INCIDENT_STATUS_INVESTIGATING",
		3: "INCIDENT_STATUS_CONTAINED",
		4: "INCIDENT_STATUS_RESOLVED",
		5: "INCIDENT_STATUS_CLOSED",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_STATUS_UNSPECIFIED":   0,
		"INCIDENT_STATUS_OPEN":          1,
		"INCIDENT_STATUS_INVESTIGATING": 2,
		"INCIDENT_STATUS_CONTAINED":     3,
		"INCIDENT_STATUS_RESOLVED":      4,
		"INCIDENT_STATUS_CLOSED":        5,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_detection_proto_enumTypes[1].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_detection_proto_enumTypes[1]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_detection_proto_rawDescGZIP(), []int{1}
}

type Detection struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId   string                 `protobuf:"bytes,2,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
	RuleName string                 `protobuf:"bytes,3,opt,name=rule_name,proto3" json:"rule_name,omitempty"`
	// At least one triggering TelemetryEvent.id. Non-empty by contract
	// (enforced in JSON Schema; proto3 cannot express cardinality).
	TelemetryEventIds []string               `protobuf:"bytes,4,rep,name=telemetry_event_ids,proto3" json:"telemetry_event_ids,omitempty"`
	DetectedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=detected_at,proto3" json:"detected_at,omitempty"`
	Severity          Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=blueveil.contracts.v1.Severity" json:"severity,omitempty"`
	// Rule confidence in [0.0, 1.0]. Range enforced in JSON Schema.
	Confidence    float64           `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Title         string            `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description   string            `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Attributes    map[string]string `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_detection_proto_rawDescGZIP(), []int{0}
}

func (x *Detection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Detection) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Detection) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Detection) GetTelemetryEventIds() []string {
	if x != nil {
		return x.TelemetryEventIds
	}
	return nil
}

func (x *Detection) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *Detection) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Detection) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Detection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Detection) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectionIds  []string               `protobuf:"bytes,2,rep,name=detection_ids,proto3" json:"detection_ids,omitempty"`
	Status        AlertStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=blueveil.contracts.v1.AlertStatus" json:"status,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=blueveil.contracts.v1.Severity" json:"severity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_detection_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetDetectionIds() []string {
	if x != nil {
		return x.DetectionIds
	}
	return nil
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertIds      []string               `protobuf:"bytes,2,rep,name=alert_ids,proto3" json:"alert_ids,omitempty"`
	Status        IncidentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=blueveil.contracts.v1.IncidentStatus" json:"status,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=blueveil.contracts.v1.Severity" json:"severity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_detection_proto_rawDescGZIP(), []int{2}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetAlertIds() []string {
	if x != nil {
		return x.AlertIds
	}
	return nil
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *Incident) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Incident) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_blueveil_contracts_v1_detection_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_detection_proto_rawDesc = "" +
	"\n" +
	"%blueveil/contracts/v1/detection.proto\x12\x15blueveil.contracts.v1\x1a\"blueveil/contracts/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x03\n" +
	"\tDetection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\arule_id\x18\x02 \x01(\tR\arule_id\x12\x1c\n" +
	"\trule_name\x18\x03 \x01(\tR\trule_name\x120\n" +
	"\x13telemetry_event_ids\x18\x04 \x03(\tR\x13telemetry_event_ids\x12<\n" +
	"\vdetected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdetected_at\x12;\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x1f.blueveil.contracts.v1.SeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12P\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v20.blueveil.contracts.v1.Detection.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rdetection_ids\x18\x02 \x03(\tR\rdetection_ids\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".blueveil.contracts.v1.AlertStatusR\x06status\x12;\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1f.blueveil.contracts.v1.SeverityR\bseverity\x12:\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\"\xdc\x02\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\talert_ids\x18\x02 \x03(\tR\talert_ids\x12=\n" +
	"\x06status\x18\x03 \x01(\x0e2%.blueveil.contracts.v1.IncidentStatusR\x06status\x12;\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1f.blueveil.contracts.v1.SeverityR\bseverity\x12:\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary*z\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ALERT_STATUS_OPEN\x10\x01\x12\x1d\n" +
	"\x19ALERT_STATUS_ACKNOWLEDGED\x10\x02\x12\x17\n" +
	"\x13ALERT_STATUS_CLOSED\x10\x03*\xc7\x01\n" +
	"\x0eIncidentStatus\x12\x1f\n" +
	"\x1bINCIDENT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INCIDENT_STATUS_OPEN\x10\x01\x12!\n" +
	"\x1dINCIDENT_STATUS_INVESTIGATING\x10\x02\x12\x1d\n" +
	"\x19INCIDENT_STATUS_CONTAINED\x10\x03\x12\x1c\n" +
	"\x18INCIDENT_STATUS_RESOLVED\x10\x04\x12\x1a\n" +
	"\x16INCIDENT_STATUS_CLOSED\x10\x05b\x06proto3"

var (
	file_blueveil_contracts_v1_detection_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_detection_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_detection_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_detection_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_detection_proto_rawDesc), len(file_blueveil_contracts_v1_detection_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_detection_proto_rawDescData
}

var file_blueveil_contracts_v1_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blueveil_contracts_v1_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blueveil_contracts_v1_detection_proto_goTypes = []any{
	(AlertStatus)(0),              // 0: blueveil.contracts.v1.AlertStatus
	(IncidentStatus)(0),           // 1: blueveil.contracts.v1.IncidentStatus
	(*Detection)(nil),             // 2: blueveil.contracts.v1.Detection
	(*Alert)(nil),                 // 3: blueveil.contracts.v1.Alert
	(*Incident)(nil),              // 4: blueveil.contracts.v1.Incident
	nil,                           // 5: blueveil.contracts.v1.Detection.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(Severity)(0),                 // 7: blueveil.contracts.v1.Severity
}
var file_blueveil_contracts_v1_detection_proto_depIdxs = []int32{
	6,  // 0: blueveil.contracts.v1.Detection.detected_at:type_name -> google.protobuf.Timestamp
	7,  // 1: blueveil.contracts.v1.Detection.severity:type_name -> blueveil.contracts.v1.Severity
	5,  // 2: blueveil.contracts.v1.Detection.attributes:type_name -> blueveil.contracts.v1.Detection.AttributesEntry
	0,  // 3: blueveil.contracts.v1.Alert.status:type_name -> blueveil.contracts.v1.AlertStatus
	7,  // 4: blueveil.contracts.v1.Alert.severity:type_name -> blueveil.contracts.v1.Severity
	6,  // 5: blueveil.contracts.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: blueveil.contracts.v1.Alert.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: blueveil.contracts.v1.Incident.status:type_name -> blueveil.contracts.v1.IncidentStatus
	7,  // 8: blueveil.contracts.v1.Incident.severity:type_name -> blueveil.contracts.v1.Severity
	6,  // 9: blueveil.contracts.v1.Incident.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: blueveil.contracts.v1.Incident.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_detection_proto_init() }
func file_blueveil_contracts_v1_detection_proto_init() {
	if File_blueveil_contracts_v1_detection_proto != nil {
		return
	}
	file_blueveil_contracts_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_detection_proto_rawDesc), len(file_blueveil_contracts_v1_detection_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_detection_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_detection_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_detection_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_detection_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_detection_proto = out.File
	file_blueveil_contracts_v1_detection_proto_goTypes = nil
	file_blueveil_contracts_v1_detection_proto_depIdxs = nil
}
