// Evidence contract — blueveil.contracts.v1.
// Evidence is always attached to an incident and is content-addressed
// when a hash is available (sha256 optional, lowercase hex when present).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/evidence.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceType int32

const (
	EvidenceType_EVIDENCE_TYPE_UNSPECIFIED   EvidenceType = 0
	EvidenceType_EVIDENCE_TYPE_LOG_EXCERPT   EvidenceType = 1
	EvidenceType_EVIDENCE_TYPE_HTTP_REQUEST  EvidenceType = 2
	EvidenceType_EVIDENCE_TYPE_HTTP_RESPONSE EvidenceType = 3
	EvidenceType_EVIDENCE_TYPE_SCAN_RESULT   EvidenceType = 4
	EvidenceType_EVIDENCE_TYPE_FILE_HASH     EvidenceType = 5
	EvidenceType_EVIDENCE_TYPE_NOTE          EvidenceType = 6
)

// Enum value maps for EvidenceType.
var (
	EvidenceType_name = map[int32]string{
		0: "EVIDENCE_TYPE_UNSPECIFIED",
		1: "EVIDENCE_TYPE_LOG_EXCERPT",
		2: "EVIDENCE_TYPE_HTTP_REQUEST",
		3: "EVIDENCE_TYPE_HTTP_RESPONSE",
		4: "EVIDENCE_TYPE_SCAN_RESULT",
		5: "EVIDENCE_TYPE_FILE_HASH",
		6: "EVIDENCE_TYPE_NOTE",
	}
	EvidenceType_value = map[string]int32{
		"EVIDENCE_TYPE_UNSPECIFIED":   0,
		"EVIDENCE_TYPE_LOG_EXCERPT":   1,
		"EVIDENCE_TYPE_HTTP_REQUEST":  2,
		"EVIDENCE_TYPE_HTTP_RESPONSE": 3,
		"EVIDENCE_TYPE_SCAN_RESULT":   4,
		"EVIDENCE_TYPE_FILE_HASH":     5,
		"EVIDENCE_TYPE_NOTE":          6,
	}
)

func (x EvidenceType) Enum() *EvidenceType {
	p := new(EvidenceType)
	*p = x
	return p
}

func (x EvidenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_evidence_proto_enumTypes[0].Descriptor()
}

func (EvidenceType) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_evidence_proto_enumTypes[0]
}

func (x EvidenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceType.Descriptor instead.
func (EvidenceType) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_evidence_proto_rawDescGZIP(), []int{0}
}

type Evidence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning Incident.id.
	IncidentId  string                 `protobuf:"bytes,2,opt,name=incident_id,proto3" json:"incident_id,omitempty"`
	Type        EvidenceType           `protobuf:"varint,3,opt,name=type,proto3,enum=blueveil.contracts.v1.EvidenceType" json:"type,omitempty"`
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=collected_at,proto3" json:"collected_at,omitempty"`
	// Where the evidence came from, e.g. "waf-sim", "analyst-note".
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// MIME type of content, e.g. "application/json", "text/plain".
	MediaType string `protobuf:"bytes,6,opt,name=media_type,proto3" json:"media_type,omitempty"`
	// Lowercase hex SHA-256 of content when available; empty otherwise.
	Sha256 string `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Inline content. Large blobs are out of scope for v1 (a content
	// reference contract arrives with object storage support, not here).
	Content       string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_blueveil_contracts_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Evidence) GetType() EvidenceType {
	if x != nil {
		return x.Type
	}
	return EvidenceType_EVIDENCE_TYPE_UNSPECIFIED
}

func (x *Evidence) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *Evidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Evidence) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Evidence) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Evidence) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_blueveil_contracts_v1_evidence_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_evidence_proto_rawDesc = "" +
	"\n" +
	"$blueveil/contracts/v1/evidence.proto\x12\x15blueveil.contracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vincident_id\x18\x02 \x01(\tR\vincident_id\x127\n" +
	"\x04type\x18\x03 \x01(\x0e2#.blueveil.contracts.v1.EvidenceTypeR\x04type\x12>\n" +
	"\fcollected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcollected_at\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\n" +
	"media_type\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent*\xe1\x01\n" +
	"\fEvidenceType\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_LOG_EXCERPT\x10\x01\x12\x1e\n" +
	"\x1aEVIDENCE_TYPE_HTTP_REQUEST\x10\x02\x12\x1f\n" +
	"\x1bEVIDENCE_TYPE_HTTP_RESPONSE\x10\x03\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_SCAN_RESULT\x10\x04\x12\x1b\n" +
	"\x17EVIDENCE_TYPE_FILE_HASH\x10\x05\x12\x16\n" +
	"\x12EVIDENCE_TYPE_NOTE\x10\x06b\x06proto3"

var (
	file_blueveil_contracts_v1_evidence_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_evidence_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_evidence_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_evidence_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_evidence_proto_rawDesc), len(file_blueveil_contracts_v1_evidence_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_evidence_proto_rawDescData
}

var file_blueveil_contracts_v1_evidence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blueveil_contracts_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blueveil_contracts_v1_evidence_proto_goTypes = []any{
	(EvidenceType)(0),             // 0: blueveil.contracts.v1.EvidenceType
	(*Evidence)(nil),              // 1: blueveil.contracts.v1.Evidence
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_blueveil_contracts_v1_evidence_proto_depIdxs = []int32{
	0, // 0: blueveil.contracts.v1.Evidence.type:type_name -> blueveil.contracts.v1.EvidenceType
	2, // 1: blueveil.contracts.v1.Evidence.collected_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_evidence_proto_init() }
func file_blueveil_contracts_v1_evidence_proto_init() {
	if File_blueveil_contracts_v1_evidence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_evidence_proto_rawDesc), len(file_blueveil_contracts_v1_evidence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_evidence_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_evidence_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_evidence_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_evidence_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_evidence_proto = out.File
	file_blueveil_contracts_v1_evidence_proto_goTypes = nil
	file_blueveil_contracts_v1_evidence_proto_depIdxs = nil
}
