// Identity contract — blueveil.contracts.v1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/identity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED     IdentityType = 0
	IdentityType_IDENTITY_TYPE_USER            IdentityType = 1
	IdentityType_IDENTITY_TYPE_SERVICE_ACCOUNT IdentityType = 2
	IdentityType_IDENTITY_TYPE_WORKLOAD        IdentityType = 3
	IdentityType_IDENTITY_TYPE_ANONYMOUS       IdentityType = 4
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_USER",
		2: "IDENTITY_TYPE_SERVICE_ACCOUNT",
		3: "IDENTITY_TYPE_WORKLOAD",
		4: "IDENTITY_TYPE_ANONYMOUS",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED":     0,
		"IDENTITY_TYPE_USER":            1,
		"IDENTITY_TYPE_SERVICE_ACCOUNT": 2,
		"IDENTITY_TYPE_WORKLOAD":        3,
		"IDENTITY_TYPE_ANONYMOUS":       4,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_identity_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_identity_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_identity_proto_rawDescGZIP(), []int{0}
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          IdentityType           `protobuf:"varint,2,opt,name=type,proto3,enum=blueveil.contracts.v1.IdentityType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_blueveil_contracts_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetType() IdentityType {
	if x != nil {
		return x.Type
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_blueveil_contracts_v1_identity_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_identity_proto_rawDesc = "" +
	"\n" +
	"$blueveil/contracts/v1/identity.proto\x12\x15blueveil.contracts.v1\"g\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.blueveil.contracts.v1.IdentityTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name*\xa1\x01\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12IDENTITY_TYPE_USER\x10\x01\x12!\n" +
	"\x1dIDENTITY_TYPE_SERVICE_ACCOUNT\x10\x02\x12\x1a\n" +
	"\x16IDENTITY_TYPE_WORKLOAD\x10\x03\x12\x1b\n" +
	"\x17IDENTITY_TYPE_ANONYMOUS\x10\x04b\x06proto3"

var (
	file_blueveil_contracts_v1_identity_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_identity_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_identity_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_identity_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_identity_proto_rawDesc), len(file_blueveil_contracts_v1_identity_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_identity_proto_rawDescData
}

var file_blueveil_contracts_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blueveil_contracts_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blueveil_contracts_v1_identity_proto_goTypes = []any{
	(IdentityType)(0), // 0: blueveil.contracts.v1.IdentityType
	(*Identity)(nil),  // 1: blueveil.contracts.v1.Identity
}
var file_blueveil_contracts_v1_identity_proto_depIdxs = []int32{
	0, // 0: blueveil.contracts.v1.Identity.type:type_name -> blueveil.contracts.v1.IdentityType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_identity_proto_init() }
func file_blueveil_contracts_v1_identity_proto_init() {
	if File_blueveil_contracts_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_identity_proto_rawDesc), len(file_blueveil_contracts_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_identity_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_identity_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_identity_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_identity_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_identity_proto = out.File
	file_blueveil_contracts_v1_identity_proto_goTypes = nil
	file_blueveil_contracts_v1_identity_proto_depIdxs = nil
}
