// Response contracts — blueveil.contracts.v1 (additive, Step 8).
// Owned by Blueveil. These messages give the safety-governed response layer
// a language-neutral representation: recommendation, human/policy approval,
// execution record, verification outcome. Audit stays code-level (Rust
// audit.rs + Go audit log with identical field semantics) until a dedicated
// audit contract is justified — not speculatively here.
//
// Deliberately absent: SUCCESS, SECURE, PASSED. Outcomes stay explicit
// (EXECUTED vs VERIFIED vs UNKNOWN are different claims).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/response.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation type, deliberately independent from RiskLevel. Mirrors the
// approved Blueveil operation taxonomy (and Rust core policy::Operation).
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_READ        OperationType = 1
	OperationType_OPERATION_TYPE_OBSERVE     OperationType = 2
	OperationType_OPERATION_TYPE_ANALYZE     OperationType = 3
	OperationType_OPERATION_TYPE_RECOMMEND   OperationType = 4
	OperationType_OPERATION_TYPE_WRITE       OperationType = 5
	OperationType_OPERATION_TYPE_MODIFY      OperationType = 6
	OperationType_OPERATION_TYPE_BLOCK       OperationType = 7
	OperationType_OPERATION_TYPE_ISOLATE     OperationType = 8
	OperationType_OPERATION_TYPE_DELETE      OperationType = 9
	OperationType_OPERATION_TYPE_EXECUTE     OperationType = 10
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0:  "OPERATION_TYPE_UNSPECIFIED",
		1:  "OPERATION_TYPE_READ",
		2:  "OPERATION_TYPE_OBSERVE",
		3:  "OPERATION_TYPE_ANALYZE",
		4:  "OPERATION_TYPE_RECOMMEND",
		5:  "OPERATION_TYPE_WRITE",
		6:  "OPERATION_TYPE_MODIFY",
		7:  "OPERATION_TYPE_BLOCK",
		8:  "OPERATION_TYPE_ISOLATE",
		9:  "OPERATION_TYPE_DELETE",
		10: "OPERATION_TYPE_EXECUTE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_READ":        1,
		"OPERATION_TYPE_OBSERVE":     2,
		"OPERATION_TYPE_ANALYZE":     3,
		"OPERATION_TYPE_RECOMMEND":   4,
		"OPERATION_TYPE_WRITE":       5,
		"OPERATION_TYPE_MODIFY":      6,
		"OPERATION_TYPE_BLOCK":       7,
		"OPERATION_TYPE_ISOLATE":     8,
		"OPERATION_TYPE_DELETE":      9,
		"OPERATION_TYPE_EXECUTE":     10,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_response_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_response_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{0}
}

// Risk/impact level, independent from OperationType. A HIGH operation never
// implies BLOCK; policy always decides.
type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 4
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
		4: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
		"RISK_LEVEL_CRITICAL":    4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_response_proto_enumTypes[1].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_response_proto_enumTypes[1]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{1}
}

// Lifecycle status tracked on a ResponseRecommendation. Terminal states:
// DENIED, EXECUTION_FAILED (after failed verification), VERIFIED,
// VERIFICATION_FAILED, VERIFICATION_UNKNOWN.
type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED ResponseStatus = 0
	// Recommendation recorded, undecided.
	ResponseStatus_RESPONSE_STATUS_PROPOSED ResponseStatus = 1
	// Policy requires human approval before execution.
	ResponseStatus_RESPONSE_STATUS_PENDING_APPROVAL ResponseStatus = 2
	// Authorized (by policy directly, or by a recorded approval).
	ResponseStatus_RESPONSE_STATUS_APPROVED ResponseStatus = 3
	// Policy refused. Terminal.
	ResponseStatus_RESPONSE_STATUS_DENIED ResponseStatus = 4
	// Handed to the executor (transient; never a final claim).
	ResponseStatus_RESPONSE_STATUS_EXECUTING ResponseStatus = 5
	// Executor reported success. NOT "secured" — verification still pending.
	ResponseStatus_RESPONSE_STATUS_EXECUTED ResponseStatus = 6
	// Executor reported failure.
	ResponseStatus_RESPONSE_STATUS_EXECUTION_FAILED ResponseStatus = 7
	// Verification confirmed the response intent.
	ResponseStatus_RESPONSE_STATUS_VERIFIED ResponseStatus = 8
	// Verification disproved the response intent.
	ResponseStatus_RESPONSE_STATUS_VERIFICATION_FAILED ResponseStatus = 9
	// No verification source: unknown, never verified.
	ResponseStatus_RESPONSE_STATUS_VERIFICATION_UNKNOWN ResponseStatus = 10
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0:  "RESPONSE_STATUS_UNSPECIFIED",
		1:  "RESPONSE_STATUS_PROPOSED",
		2:  "RESPONSE_STATUS_PENDING_APPROVAL",
		3:  "RESPONSE_STATUS_APPROVED",
		4:  "RESPONSE_STATUS_DENIED",
		5:  "RESPONSE_STATUS_EXECUTING",
		6:  "RESPONSE_STATUS_EXECUTED",
		7:  "RESPONSE_STATUS_EXECUTION_FAILED",
		8:  "RESPONSE_STATUS_VERIFIED",
		9:  "RESPONSE_STATUS_VERIFICATION_FAILED",
		10: "RESPONSE_STATUS_VERIFICATION_UNKNOWN",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED":          0,
		"RESPONSE_STATUS_PROPOSED":             1,
		"RESPONSE_STATUS_PENDING_APPROVAL":     2,
		"RESPONSE_STATUS_APPROVED":             3,
		"RESPONSE_STATUS_DENIED":               4,
		"RESPONSE_STATUS_EXECUTING":            5,
		"RESPONSE_STATUS_EXECUTED":             6,
		"RESPONSE_STATUS_EXECUTION_FAILED":     7,
		"RESPONSE_STATUS_VERIFIED":             8,
		"RESPONSE_STATUS_VERIFICATION_FAILED":  9,
		"RESPONSE_STATUS_VERIFICATION_UNKNOWN": 10,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_response_proto_enumTypes[2].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_response_proto_enumTypes[2]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{2}
}

// Verification outcome, separate from execution outcome by design:
// a successful execution is not a verified response.
type VerificationOutcome int32

const (
	VerificationOutcome_VERIFICATION_OUTCOME_UNSPECIFIED VerificationOutcome = 0
	VerificationOutcome_VERIFICATION_OUTCOME_VERIFIED    VerificationOutcome = 1
	VerificationOutcome_VERIFICATION_OUTCOME_FAILED      VerificationOutcome = 2
	VerificationOutcome_VERIFICATION_OUTCOME_UNKNOWN     VerificationOutcome = 3
)

// Enum value maps for VerificationOutcome.
var (
	VerificationOutcome_name = map[int32]string{
		0: "VERIFICATION_OUTCOME_UNSPECIFIED",
		1: "VERIFICATION_OUTCOME_VERIFIED",
		2: "VERIFICATION_OUTCOME_FAILED",
		3: "VERIFICATION_OUTCOME_UNKNOWN",
	}
	VerificationOutcome_value = map[string]int32{
		"VERIFICATION_OUTCOME_UNSPECIFIED": 0,
		"VERIFICATION_OUTCOME_VERIFIED":    1,
		"VERIFICATION_OUTCOME_FAILED":      2,
		"VERIFICATION_OUTCOME_UNKNOWN":     3,
	}
)

func (x VerificationOutcome) Enum() *VerificationOutcome {
	p := new(VerificationOutcome)
	*p = x
	return p
}

func (x VerificationOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_response_proto_enumTypes[3].Descriptor()
}

func (VerificationOutcome) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_response_proto_enumTypes[3]
}

func (x VerificationOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationOutcome.Descriptor instead.
func (VerificationOutcome) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{3}
}

// A proposed response to an incident. Data, not authorization: creating one
// permits nothing.
type ResponseRecommendation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning Incident.id.
	IncidentId string        `protobuf:"bytes,2,opt,name=incident_id,proto3" json:"incident_id,omitempty"`
	Operation  OperationType `protobuf:"varint,3,opt,name=operation,proto3,enum=blueveil.contracts.v1.OperationType" json:"operation,omitempty"`
	// What the operation would observe/affect (asset ids, joined when many).
	Target string    `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Risk   RiskLevel `protobuf:"varint,5,opt,name=risk,proto3,enum=blueveil.contracts.v1.RiskLevel" json:"risk,omitempty"`
	// Why this is proposed, citing incident data only — never attacker intent.
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=blueveil.contracts.v1.ResponseStatus" json:"status,omitempty"`
	RecommendedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=recommended_at,proto3" json:"recommended_at,omitempty"`
	// Component identity that proposed this (e.g. "blueveil-recommender/1"),
	// never a fabricated human.
	RecommendedBy string `protobuf:"bytes,9,opt,name=recommended_by,proto3" json:"recommended_by,omitempty"`
	// Advisory flag mirroring the safety gate rule; policy re-evaluates
	// independently and never trusts this flag.
	ApprovalRequired bool `protobuf:"varint,10,opt,name=approval_required,proto3" json:"approval_required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseRecommendation) Reset() {
	*x = ResponseRecommendation{}
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRecommendation) ProtoMessage() {}

func (x *ResponseRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRecommendation.ProtoReflect.Descriptor instead.
func (*ResponseRecommendation) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseRecommendation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseRecommendation) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *ResponseRecommendation) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *ResponseRecommendation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResponseRecommendation) GetRisk() RiskLevel {
	if x != nil {
		return x.Risk
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *ResponseRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResponseRecommendation) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *ResponseRecommendation) GetRecommendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecommendedAt
	}
	return nil
}

func (x *ResponseRecommendation) GetRecommendedBy() string {
	if x != nil {
		return x.RecommendedBy
	}
	return ""
}

func (x *ResponseRecommendation) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

// A human approval bound to exactly one recommendation. Binding fields
// (recommendation_id, operation, target, risk) must all match at use;
// an approval for BLOCK target-A never authorizes DELETE target-B.
type ResponseApproval struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecommendationId string                 `protobuf:"bytes,2,opt,name=recommendation_id,proto3" json:"recommendation_id,omitempty"`
	Operation        OperationType          `protobuf:"varint,3,opt,name=operation,proto3,enum=blueveil.contracts.v1.OperationType" json:"operation,omitempty"`
	Target           string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Risk             RiskLevel              `protobuf:"varint,5,opt,name=risk,proto3,enum=blueveil.contracts.v1.RiskLevel" json:"risk,omitempty"`
	// Explicit actor identity (synthetic test actors must be labeled as such).
	Approver   string                 `protobuf:"bytes,6,opt,name=approver,proto3" json:"approver,omitempty"`
	ApprovedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=approved_at,proto3" json:"approved_at,omitempty"`
	// Optional expiry; absent means no expiry. Expired approvals reject.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseApproval) Reset() {
	*x = ResponseApproval{}
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseApproval) ProtoMessage() {}

func (x *ResponseApproval) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseApproval.ProtoReflect.Descriptor instead.
func (*ResponseApproval) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseApproval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseApproval) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *ResponseApproval) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *ResponseApproval) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResponseApproval) GetRisk() RiskLevel {
	if x != nil {
		return x.Risk
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *ResponseApproval) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ResponseApproval) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *ResponseApproval) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ResponseApproval) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// The executor's report. success = "the executor did what was asked".
// It is NOT "the system is secured" — only verification can speak to that.
type ResponseExecution struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecommendationId string                 `protobuf:"bytes,2,opt,name=recommendation_id,proto3" json:"recommendation_id,omitempty"`
	// Empty when policy authorized without human approval.
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,proto3" json:"approval_id,omitempty"`
	Operation     OperationType          `protobuf:"varint,4,opt,name=operation,proto3,enum=blueveil.contracts.v1.OperationType" json:"operation,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,proto3" json:"finished_at,omitempty"`
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	Detail        string                 `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseExecution) Reset() {
	*x = ResponseExecution{}
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExecution) ProtoMessage() {}

func (x *ResponseExecution) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExecution.ProtoReflect.Descriptor instead.
func (*ResponseExecution) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseExecution) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *ResponseExecution) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ResponseExecution) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *ResponseExecution) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResponseExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ResponseExecution) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ResponseExecution) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseExecution) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// The verification verdict over one execution.
type ResponseVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,proto3" json:"execution_id,omitempty"`
	Outcome       VerificationOutcome    `protobuf:"varint,3,opt,name=outcome,proto3,enum=blueveil.contracts.v1.VerificationOutcome" json:"outcome,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=verified_at,proto3" json:"verified_at,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseVerification) Reset() {
	*x = ResponseVerification{}
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVerification) ProtoMessage() {}

func (x *ResponseVerification) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVerification.ProtoReflect.Descriptor instead.
func (*ResponseVerification) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseVerification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseVerification) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ResponseVerification) GetOutcome() VerificationOutcome {
	if x != nil {
		return x.Outcome
	}
	return VerificationOutcome_VERIFICATION_OUTCOME_UNSPECIFIED
}

func (x *ResponseVerification) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *ResponseVerification) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_blueveil_contracts_v1_response_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_response_proto_rawDesc = "" +
	"\n" +
	"$blueveil/contracts/v1/response.proto\x12\x15blueveil.contracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x03\n" +
	"\x16ResponseRecommendation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vincident_id\x18\x02 \x01(\tR\vincident_id\x12B\n" +
	"\toperation\x18\x03 \x01(\x0e2$.blueveil.contracts.v1.OperationTypeR\toperation\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x124\n" +
	"\x04risk\x18\x05 \x01(\x0e2 .blueveil.contracts.v1.RiskLevelR\x04risk\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.blueveil.contracts.v1.ResponseStatusR\x06status\x12B\n" +
	"\x0erecommended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0erecommended_at\x12&\n" +
	"\x0erecommended_by\x18\t \x01(\tR\x0erecommended_by\x12,\n" +
	"\x11approval_required\x18\n" +
	" \x01(\bR\x11approval_required\"\x90\x03\n" +
	"\x10ResponseApproval\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11recommendation_id\x18\x02 \x01(\tR\x11recommendation_id\x12B\n" +
	"\toperation\x18\x03 \x01(\x0e2$.blueveil.contracts.v1.OperationTypeR\toperation\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x124\n" +
	"\x04risk\x18\x05 \x01(\x0e2 .blueveil.contracts.v1.RiskLevelR\x04risk\x12\x1a\n" +
	"\bapprover\x18\x06 \x01(\tR\bapprover\x12<\n" +
	"\vapproved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vapproved_at\x12:\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expires_at\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\"\xfb\x02\n" +
	"\x11ResponseExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11recommendation_id\x18\x02 \x01(\tR\x11recommendation_id\x12 \n" +
	"\vapproval_id\x18\x03 \x01(\tR\vapproval_id\x12B\n" +
	"\toperation\x18\x04 \x01(\x0e2$.blueveil.contracts.v1.OperationTypeR\toperation\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12:\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"started_at\x12<\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vfinished_at\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\"\xe6\x01\n" +
	"\x14ResponseVerification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fexecution_id\x18\x02 \x01(\tR\fexecution_id\x12D\n" +
	"\aoutcome\x18\x03 \x01(\x0e2*.blueveil.contracts.v1.VerificationOutcomeR\aoutcome\x12<\n" +
	"\vverified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vverified_at\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail*\xc0\x02\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OPERATION_TYPE_READ\x10\x01\x12\x1a\n" +
	"\x16OPERATION_TYPE_OBSERVE\x10\x02\x12\x1a\n" +
	"\x16OPERATION_TYPE_ANALYZE\x10\x03\x12\x1c\n" +
	"\x18OPERATION_TYPE_RECOMMEND\x10\x04\x12\x18\n" +
	"\x14OPERATION_TYPE_WRITE\x10\x05\x12\x19\n" +
	"\x15OPERATION_TYPE_MODIFY\x10\x06\x12\x18\n" +
	"\x14OPERATION_TYPE_BLOCK\x10\a\x12\x1a\n" +
	"\x16OPERATION_TYPE_ISOLATE\x10\b\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\t\x12\x1a\n" +
	"\x16OPERATION_TYPE_EXECUTE\x10\n" +
	"*\x80\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x04*\x83\x03\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RESPONSE_STATUS_PROPOSED\x10\x01\x12$\n" +
	" RESPONSE_STATUS_PENDING_APPROVAL\x10\x02\x12\x1c\n" +
	"\x18RESPONSE_STATUS_APPROVED\x10\x03\x12\x1a\n" +
	"\x16RESPONSE_STATUS_DENIED\x10\x04\x12\x1d\n" +
	"\x19RESPONSE_STATUS_EXECUTING\x10\x05\x12\x1c\n" +
	"\x18RESPONSE_STATUS_EXECUTED\x10\x06\x12$\n" +
	" RESPONSE_STATUS_EXECUTION_FAILED\x10\a\x12\x1c\n" +
	"\x18RESPONSE_STATUS_VERIFIED\x10\b\x12'\n" +
	"#RESPONSE_STATUS_VERIFICATION_FAILED\x10\t\x12(\n" +
	"$RESPONSE_STATUS_VERIFICATION_UNKNOWN\x10\n" +
	"*\xa1\x01\n" +
	"\x13VerificationOutcome\x12$\n" +
	" VERIFICATION_OUTCOME_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVERIFICATION_OUTCOME_VERIFIED\x10\x01\x12\x1f\n" +
	"\x1bVERIFICATION_OUTCOME_FAILED\x10\x02\x12 \n" +
	"\x1cVERIFICATION_OUTCOME_UNKNOWN\x10\x03b\x06proto3"

var (
	file_blueveil_contracts_v1_response_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_response_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_response_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_response_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_response_proto_rawDesc), len(file_blueveil_contracts_v1_response_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_response_proto_rawDescData
}

var file_blueveil_contracts_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_blueveil_contracts_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blueveil_contracts_v1_response_proto_goTypes = []any{
	(OperationType)(0),             // 0: blueveil.contracts.v1.OperationType
	(RiskLevel)(0),                 // 1: blueveil.contracts.v1.RiskLevel
	(ResponseStatus)(0),            // 2: blueveil.contracts.v1.ResponseStatus
	(VerificationOutcome)(0),       // 3: blueveil.contracts.v1.VerificationOutcome
	(*ResponseRecommendation)(nil), // 4: blueveil.contracts.v1.ResponseRecommendation
	(*ResponseApproval)(nil),       // 5: blueveil.contracts.v1.ResponseApproval
	(*ResponseExecution)(nil),      // 6: blueveil.contracts.v1.ResponseExecution
	(*ResponseVerification)(nil),   // 7: blueveil.contracts.v1.ResponseVerification
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_blueveil_contracts_v1_response_proto_depIdxs = []int32{
	0,  // 0: blueveil.contracts.v1.ResponseRecommendation.operation:type_name -> blueveil.contracts.v1.OperationType
	1,  // 1: blueveil.contracts.v1.ResponseRecommendation.risk:type_name -> blueveil.contracts.v1.RiskLevel
	2,  // 2: blueveil.contracts.v1.ResponseRecommendation.status:type_name -> blueveil.contracts.v1.ResponseStatus
	8,  // 3: blueveil.contracts.v1.ResponseRecommendation.recommended_at:type_name -> google.protobuf.Timestamp
	0,  // 4: blueveil.contracts.v1.ResponseApproval.operation:type_name -> blueveil.contracts.v1.OperationType
	1,  // 5: blueveil.contracts.v1.ResponseApproval.risk:type_name -> blueveil.contracts.v1.RiskLevel
	8,  // 6: blueveil.contracts.v1.ResponseApproval.approved_at:type_name -> google.protobuf.Timestamp
	8,  // 7: blueveil.contracts.v1.ResponseApproval.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 8: blueveil.contracts.v1.ResponseExecution.operation:type_name -> blueveil.contracts.v1.OperationType
	8,  // 9: blueveil.contracts.v1.ResponseExecution.started_at:type_name -> google.protobuf.Timestamp
	8,  // 10: blueveil.contracts.v1.ResponseExecution.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 11: blueveil.contracts.v1.ResponseVerification.outcome:type_name -> blueveil.contracts.v1.VerificationOutcome
	8,  // 12: blueveil.contracts.v1.ResponseVerification.verified_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_response_proto_init() }
func file_blueveil_contracts_v1_response_proto_init() {
	if File_blueveil_contracts_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_response_proto_rawDesc), len(file_blueveil_contracts_v1_response_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_response_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_response_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_response_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_response_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_response_proto = out.File
	file_blueveil_contracts_v1_response_proto_goTypes = nil
	file_blueveil_contracts_v1_response_proto_depIdxs = nil
}
