// TelemetryEvent contract — blueveil.contracts.v1.
// Canonical JSON uses snake_case field names (see explicit json_name options
// and contracts/README.md). Timestamps are RFC 3339 (proto JSON mapping).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/telemetry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,proto3" json:"occurred_at,omitempty"`
	// Collector/source name, e.g. "waf-sim". Free string; the source registry
	// arrives with a later contract, not here.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Reference to Asset.id.
	AssetId string `protobuf:"bytes,4,opt,name=asset_id,proto3" json:"asset_id,omitempty"`
	// Optional reference to Identity.id.
	IdentityId string `protobuf:"bytes,5,opt,name=identity_id,proto3" json:"identity_id,omitempty"`
	// Source-namespaced event type, e.g. "waf.request_blocked".
	EventType  string            `protobuf:"bytes,6,opt,name=event_type,proto3" json:"event_type,omitempty"`
	Severity   Severity          `protobuf:"varint,7,opt,name=severity,proto3,enum=blueveil.contracts.v1.Severity" json:"severity,omitempty"`
	Attributes map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// UTF-8 excerpt of the raw record. Binary payloads are out of scope for v1;
	// producers needing binary must base64-encode and declare it in attributes.
	Raw           string `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_blueveil_contracts_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelemetryEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TelemetryEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TelemetryEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TelemetryEvent) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *TelemetryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TelemetryEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *TelemetryEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TelemetryEvent) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

var File_blueveil_contracts_v1_telemetry_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"%blueveil/contracts/v1/telemetry.proto\x12\x15blueveil.contracts.v1\x1a\"blueveil/contracts/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x03\n" +
	"\x0eTelemetryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\voccurred_at\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1a\n" +
	"\basset_id\x18\x04 \x01(\tR\basset_id\x12 \n" +
	"\videntity_id\x18\x05 \x01(\tR\videntity_id\x12\x1e\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\n" +
	"event_type\x12;\n" +
	"\bseverity\x18\a \x01(\x0e2\x1f.blueveil.contracts.v1.SeverityR\bseverity\x12U\n" +
	"\n" +
	"attributes\x18\b \x03(\v25.blueveil.contracts.v1.TelemetryEvent.AttributesEntryR\n" +
	"attributes\x12\x10\n" +
	"\x03raw\x18\t \x01(\tR\x03raw\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01b\x06proto3"

var (
	file_blueveil_contracts_v1_telemetry_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_telemetry_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_telemetry_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_telemetry_proto_rawDesc), len(file_blueveil_contracts_v1_telemetry_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_telemetry_proto_rawDescData
}

var file_blueveil_contracts_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blueveil_contracts_v1_telemetry_proto_goTypes = []any{
	(*TelemetryEvent)(nil),        // 0: blueveil.contracts.v1.TelemetryEvent
	nil,                           // 1: blueveil.contracts.v1.TelemetryEvent.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(Severity)(0),                 // 3: blueveil.contracts.v1.Severity
}
var file_blueveil_contracts_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: blueveil.contracts.v1.TelemetryEvent.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: blueveil.contracts.v1.TelemetryEvent.severity:type_name -> blueveil.contracts.v1.Severity
	1, // 2: blueveil.contracts.v1.TelemetryEvent.attributes:type_name -> blueveil.contracts.v1.TelemetryEvent.AttributesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_telemetry_proto_init() }
func file_blueveil_contracts_v1_telemetry_proto_init() {
	if File_blueveil_contracts_v1_telemetry_proto != nil {
		return
	}
	file_blueveil_contracts_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_telemetry_proto_rawDesc), len(file_blueveil_contracts_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_blueveil_contracts_v1_telemetry_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_telemetry_proto = out.File
	file_blueveil_contracts_v1_telemetry_proto_goTypes = nil
	file_blueveil_contracts_v1_telemetry_proto_depIdxs = nil
}
