// Validation contracts — blueveil.contracts.v1.
// Owned by Blueveil. A ValidationProvider (native validator, Redveil
// adapter, future scanner, mock) receives a ValidationRequest and returns
// a ValidationResult. The adapter translates provider-native output into
// THIS contract; provider internals never leak into Blueveil.
//
// Deliberate absence: there is NO "SECURE" verdict. NOT_TESTED means no
// validation was performed and MUST NOT be read as secure.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: blueveil/contracts/v1/validation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationVerdict int32

const (
	ValidationVerdict_VALIDATION_VERDICT_UNSPECIFIED ValidationVerdict = 0
	// Attack blocked; no attacker-observable effect.
	ValidationVerdict_VALIDATION_VERDICT_PREVENTED ValidationVerdict = 1
	// Attack executed but detected and logged.
	ValidationVerdict_VALIDATION_VERDICT_DETECTED ValidationVerdict = 2
	// Blocked and detected.
	ValidationVerdict_VALIDATION_VERDICT_PREVENTED_AND_DETECTED ValidationVerdict = 3
	// Attack executed AND detected: prevention failed, detection worked.
	ValidationVerdict_VALIDATION_VERDICT_ALLOWED_BUT_DETECTED ValidationVerdict = 4
	// Attack executed and NOT detected: control gap.
	ValidationVerdict_VALIDATION_VERDICT_ALLOWED_AND_NOT_DETECTED ValidationVerdict = 5
	// Request throttled: neither clean prevention nor full allowance.
	ValidationVerdict_VALIDATION_VERDICT_RATE_LIMITED ValidationVerdict = 6
	// Validation ran but the outcome is indeterminate.
	ValidationVerdict_VALIDATION_VERDICT_UNKNOWN ValidationVerdict = 7
	// No validation performed. NOT secure. NOT a pass.
	ValidationVerdict_VALIDATION_VERDICT_NOT_TESTED ValidationVerdict = 8
)

// Enum value maps for ValidationVerdict.
var (
	ValidationVerdict_name = map[int32]string{
		0: "VALIDATION_VERDICT_UNSPECIFIED",
		1: "VALIDATION_VERDICT_PREVENTED",
		2: "VALIDATION_VERDICT_DETECTED",
		3: "VALIDATION_VERDICT_PREVENTED_AND_DETECTED",
		4: "VALIDATION_VERDICT_ALLOWED_BUT_DETECTED",
		5: "VALIDATION_VERDICT_ALLOWED_AND_NOT_DETECTED",
		6: "VALIDATION_VERDICT_RATE_LIMITED",
		7: "VALIDATION_VERDICT_UNKNOWN",
		8: "VALIDATION_VERDICT_NOT_TESTED",
	}
	ValidationVerdict_value = map[string]int32{
		"VALIDATION_VERDICT_UNSPECIFIED":              0,
		"VALIDATION_VERDICT_PREVENTED":                1,
		"VALIDATION_VERDICT_DETECTED":                 2,
		"VALIDATION_VERDICT_PREVENTED_AND_DETECTED":   3,
		"VALIDATION_VERDICT_ALLOWED_BUT_DETECTED":     4,
		"VALIDATION_VERDICT_ALLOWED_AND_NOT_DETECTED": 5,
		"VALIDATION_VERDICT_RATE_LIMITED":             6,
		"VALIDATION_VERDICT_UNKNOWN":                  7,
		"VALIDATION_VERDICT_NOT_TESTED":               8,
	}
)

func (x ValidationVerdict) Enum() *ValidationVerdict {
	p := new(ValidationVerdict)
	*p = x
	return p
}

func (x ValidationVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_blueveil_contracts_v1_validation_proto_enumTypes[0].Descriptor()
}

func (ValidationVerdict) Type() protoreflect.EnumType {
	return &file_blueveil_contracts_v1_validation_proto_enumTypes[0]
}

func (x ValidationVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationVerdict.Descriptor instead.
func (ValidationVerdict) EnumDescriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_validation_proto_rawDescGZIP(), []int{0}
}

type ValidationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Control under test, e.g. "waf-xss-body-rule".
	ControlId string `protobuf:"bytes,2,opt,name=control_id,proto3" json:"control_id,omitempty"`
	// Target of the validation, e.g. an asset id or URL.
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=requested_at,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_blueveil_contracts_v1_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValidationRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ValidationRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ValidationRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ValidationRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type ValidationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning ValidationRequest.id.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,proto3" json:"request_id,omitempty"`
	ControlId string `protobuf:"bytes,3,opt,name=control_id,proto3" json:"control_id,omitempty"`
	// Provider name, e.g. "native", "redveil", "mock". Free string; the
	// provider registry arrives with a later contract, not here.
	Provider        string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderVersion string `protobuf:"bytes,5,opt,name=provider_version,proto3" json:"provider_version,omitempty"`
	// Contract version this result speaks, e.g. "blueveil.contracts.v1".
	ContractVersion string                 `protobuf:"bytes,6,opt,name=contract_version,proto3" json:"contract_version,omitempty"`
	Verdict         ValidationVerdict      `protobuf:"varint,7,opt,name=verdict,proto3,enum=blueveil.contracts.v1.ValidationVerdict" json:"verdict,omitempty"`
	ValidatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=validated_at,proto3" json:"validated_at,omitempty"`
	// References to Evidence.id supporting the verdict.
	EvidenceIds   []string `protobuf:"bytes,9,rep,name=evidence_ids,proto3" json:"evidence_ids,omitempty"`
	Note          string   `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_blueveil_contracts_v1_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_blueveil_contracts_v1_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_blueveil_contracts_v1_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValidationResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidationResult) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ValidationResult) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ValidationResult) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *ValidationResult) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *ValidationResult) GetVerdict() ValidationVerdict {
	if x != nil {
		return x.Verdict
	}
	return ValidationVerdict_VALIDATION_VERDICT_UNSPECIFIED
}

func (x *ValidationResult) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

func (x *ValidationResult) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *ValidationResult) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_blueveil_contracts_v1_validation_proto protoreflect.FileDescriptor

const file_blueveil_contracts_v1_validation_proto_rawDesc = "" +
	"\n" +
	"&blueveil/contracts/v1/validation.proto\x12\x15blueveil.contracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\x11ValidationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\n" +
	"control_id\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12O\n" +
	"\acontext\x18\x04 \x03(\v25.blueveil.contracts.v1.ValidationRequest.ContextEntryR\acontext\x12>\n" +
	"\frequested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\frequested_at\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x03\n" +
	"\x10ValidationResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\n" +
	"request_id\x12\x1e\n" +
	"\n" +
	"control_id\x18\x03 \x01(\tR\n" +
	"control_id\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12*\n" +
	"\x10provider_version\x18\x05 \x01(\tR\x10provider_version\x12*\n" +
	"\x10contract_version\x18\x06 \x01(\tR\x10contract_version\x12B\n" +
	"\averdict\x18\a \x01(\x0e2(.blueveil.contracts.v1.ValidationVerdictR\averdict\x12>\n" +
	"\fvalidated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fvalidated_at\x12\"\n" +
	"\fevidence_ids\x18\t \x03(\tR\fevidence_ids\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note*\xef\x02\n" +
	"\x11ValidationVerdict\x12\"\n" +
	"\x1eVALIDATION_VERDICT_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVALIDATION_VERDICT_PREVENTED\x10\x01\x12\x1f\n" +
	"\x1bVALIDATION_VERDICT_DETECTED\x10\x02\x12-\n" +
	")VALIDATION_VERDICT_PREVENTED_AND_DETECTED\x10\x03\x12+\n" +
	"'VALIDATION_VERDICT_ALLOWED_BUT_DETECTED\x10\x04\x12/\n" +
	"+VALIDATION_VERDICT_ALLOWED_AND_NOT_DETECTED\x10\x05\x12#\n" +
	"\x1fVALIDATION_VERDICT_RATE_LIMITED\x10\x06\x12\x1e\n" +
	"\x1aVALIDATION_VERDICT_UNKNOWN\x10\a\x12!\n" +
	"\x1dVALIDATION_VERDICT_NOT_TESTED\x10\bb\x06proto3"

var (
	file_blueveil_contracts_v1_validation_proto_rawDescOnce sync.Once
	file_blueveil_contracts_v1_validation_proto_rawDescData []byte
)

func file_blueveil_contracts_v1_validation_proto_rawDescGZIP() []byte {
	file_blueveil_contracts_v1_validation_proto_rawDescOnce.Do(func() {
		file_blueveil_contracts_v1_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_validation_proto_rawDesc), len(file_blueveil_contracts_v1_validation_proto_rawDesc)))
	})
	return file_blueveil_contracts_v1_validation_proto_rawDescData
}

var file_blueveil_contracts_v1_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blueveil_contracts_v1_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blueveil_contracts_v1_validation_proto_goTypes = []any{
	(ValidationVerdict)(0),        // 0: blueveil.contracts.v1.ValidationVerdict
	(*ValidationRequest)(nil),     // 1: blueveil.contracts.v1.ValidationRequest
	(*ValidationResult)(nil),      // 2: blueveil.contracts.v1.ValidationResult
	nil,                           // 3: blueveil.contracts.v1.ValidationRequest.ContextEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_blueveil_contracts_v1_validation_proto_depIdxs = []int32{
	3, // 0: blueveil.contracts.v1.ValidationRequest.context:type_name -> blueveil.contracts.v1.ValidationRequest.ContextEntry
	4, // 1: blueveil.contracts.v1.ValidationRequest.requested_at:type_name -> google.protobuf.Timestamp
	0, // 2: blueveil.contracts.v1.ValidationResult.verdict:type_name -> blueveil.contracts.v1.ValidationVerdict
	4, // 3: blueveil.contracts.v1.ValidationResult.validated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_blueveil_contracts_v1_validation_proto_init() }
func file_blueveil_contracts_v1_validation_proto_init() {
	if File_blueveil_contracts_v1_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blueveil_contracts_v1_validation_proto_rawDesc), len(file_blueveil_contracts_v1_validation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blueveil_contracts_v1_validation_proto_goTypes,
		DependencyIndexes: file_blueveil_contracts_v1_validation_proto_depIdxs,
		EnumInfos:         file_blueveil_contracts_v1_validation_proto_enumTypes,
		MessageInfos:      file_blueveil_contracts_v1_validation_proto_msgTypes,
	}.Build()
	File_blueveil_contracts_v1_validation_proto = out.File
	file_blueveil_contracts_v1_validation_proto_goTypes = nil
	file_blueveil_contracts_v1_validation_proto_depIdxs = nil
}
